---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.application_name | dump}}
  namespace: argocd
spec:
  destination:
    namespace: ${{values.namespace | dump}}
    server: https://kubernetes.default.svc
  project: ${{values.project_name | dump}}
  source:
    path: deploy/
    repoURL: https://github.com/Tomelin/argocd-backstage.git
    targetRevision: HEAD
