---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.project_name | dump}}
  namespace: argocd
spec:
  {% if values.description %}
  description: ${{values.description | dump}}
  {% endif %}
  destinations:
  - namespace: ${{values.namespace | dump}}

