---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# repository of Argocd
- https://github.com/Tomelin/argocd-appProject/common

patches:
# Start patche to argocd
- path: ./argocd/appProject.yaml
- path: ./argocd/application.yaml
# End patche to argocd


# echo "Hi my name is ${{ values.name }}, and you can fine me at ${{ values.url }}!"
# {% if values.enabledDB %}
# echo "You have enabled your database!"
# {% endif %}
